### ISSUE TITLE
AGCM4 usb lost written data

### ISSUE THREAD

**Issue by GMagician** [adafruit/ArduinoCore-samd#163]
I'm facing weird issue in Marlin firmware when sending a lot of data consecutively. It seems some bytes are not sent.

I'm looking ad usb code and I see in `USBDeviceClass::send` something like:

```c++
if (usbd.epBank1IsReady(ep)) {
    // previous transfer is still not complete
```
shouldn't be:
```c++
if (!usbd.epBank1IsReady(ep)) {
    // previous transfer is still not complete
```

or ready return false when ready?

**Comment by GMagician** [comment]
...seems not the cause

**Comment by GMagician** [comment]
ok, found it's using tiny usb...but `serial.write` doesnt check if it can write, it simply skip data...is it normal?

`Adafruit_USBD_CDC::write(uint8_t ch)` skip if buffer full
`Adafruit_USBD_CDC::write(const uint8_t *buffer, size_t size)` retries

**Comment by hathach** [comment]
Can you post your simple sketch that reproduce the issue? Also please tell us which board you are testing on.

**Comment by GMagician** [comment]
answer I got on PR may answer to your doubts or have I to write code?

**Comment by hathach** [comment]
the PR is more than enough, I read this issue before checking out the PR. This is fixed by #164 . Thank you very much

**Comment by GMagician** [comment]
@hathach what do you say about my original doubt:
`f (usbd.epBank1IsReady(ep)) {
    // previous transfer is still not complete`

is this test correct? I'm expecting ready return true when ready, not when busy?

**Comment by hathach** [comment]
@GMagician I have no idea, since I haven't checked out the Arduino stack. You may want to raise an issue over the original samd core. They are author, they will give a better answer than me.
